CREATE TABLE ESTUDIANTES (
 ID_ESTUDIANTE NUMBER PRIMARY KEY,
 NOMBRE VARCHAR2(100),
 APELLIDO VARCHAR2(100),
 EMAIL VARCHAR2(100) UNIQUE,
 FECHA_NACIMIENTO DATE
);
CREATE TABLE CURSOS (
 ID_CURSO NUMBER PRIMARY KEY,
 NOMBRE_CURSO VARCHAR2(100),
 DESCRIPCION VARCHAR2(255),
 DURACION NUMBER, -- Duración en horas
 PRECIO NUMBER(10, 2)
);
CREATE TABLE INSCRIPCIONES (
 ID_INSCRIPCION NUMBER PRIMARY KEY,
 ID_ESTUDIANTE NUMBER,
 ID_CURSO NUMBER,
 FECHA_INSCRIPCION DATE,
 CALIFICACION NUMBER,
 CONSTRAINT FK_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES
ESTUDIANTES(ID_ESTUDIANTE),
 CONSTRAINT FK_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(ID_CURSO)
);

ALTER TABLE ESTUDIANTES ADD DIRECCION VARCHAR2(200);

ALTER TABLE CURSOS MODIFY DURACION NUMBER(5, 1);

ALTER TABLE INSCRIPCIONES MODIFY FECHA_INSCRIPCION CONSTRAINT NN_FECHA_INSCRIPCION NOT NULL;

ALTER TABLE CURSOS ADD CONSTRAINT UQ_NOMBRE_CURSO UNIQUE (NOMBRE_CURSO);

ALTER TABLE ESTUDIANTES ADD CONSTRAINT CK_FECHA_NACIMIENTO CHECK (FECHA_NACIMIENTO <= ADD_MONTHS(SYSDATE, -192));

ALTER TABLE INSCRIPCIONES DROP CONSTRAINT FK_ESTUDIANTE;
ALTER TABLE INSCRIPCIONES ADD CONSTRAINT FK_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTES(ID_ESTUDIANTE);

ALTER TABLE CURSOS MODIFY PRECIO NUMBER(10, 2) CONSTRAINT CK_PRECIO CHECK (PRECIO >= 0);

ALTER TABLE ESTUDIANTES DROP COLUMN FECHA_NACIMIENTO;

ALTER TABLE INSCRIPCIONES RENAME COLUMN CALIFICACION TO PUNTUACION;

ALTER TABLE CURSOS DISABLE CONSTRAINT UQ_NOMBRE_CURSO;
ALTER TABLE CURSOS ENABLE CONSTRAINT UQ_NOMBRE_CURSO;
